version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dota_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: my_bot_container
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
